# Generated by Django 3.2.3 on 2021-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210520_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
