# Generated by Django 3.2.3 on 2021-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210520_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumbthumbnailUrl',
            new_name='thumbnailUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.TextField(null=True),
        ),
    ]
